name: Release Inline Encrypter plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create package
        run: |
          mkdir ${{ github.event.repository.name }}
          cp main.js manifest.json styles.css README.md ${{ github.event.repository.name }}
          zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}
    
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          mv ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}-$tag.zip
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css ${{ github.event.repository.name }}-$tag.zip
